version: '3.8'

services:
  pdf2text_api_1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PAT: ${PAT_TOKEN}
    image: pdf2text_api
    #name the container
    container_name: pdf2text_api_1
    environment:
      - PORT=5001
    env_file: .env
    volumes:
      - ./ocr_model:/root/ocr_model
    ports:
      - 5001:5001
    networks:
      - dhi

networks:
  dhi:
    name: dhi
    driver: bridge